CREATE DATABASE QL_THUVIEN;
USE QL_THUVIEN;

CREATE TABLE Adminn (
    Admin_id VARCHAR(15) NOT NULL PRIMARY KEY,
    username VARCHAR(20),
    passwordd VARCHAR(20)
);

CREATE TABLE NhanVienQuanLy (
    MaNV VARCHAR(15) NOT NULL PRIMARY KEY,
    TenNV VARCHAR(30),
    SDT INT,
    Diachi VARCHAR(30),
    FOREIGN KEY (MaNV) REFERENCES Adminn(Admin_id)
);

CREATE TABLE DocGia (
	Docgia VARCHAR(15),
    MaDG VARCHAR(15) NOT NULL PRIMARY KEY,
    TenDG VARCHAR(30),
    SDT INT,
    Diachi VARCHAR(30),
    FOREIGN KEY (Docgia) REFERENCES NhanVienQuanLy(MaNV)
);

CREATE TABLE Sach (
    MaSach VARCHAR(15) NOT NULL PRIMARY KEY,
    TenSach VARCHAR(15),
    TenTGia VARCHAR(30),
    NamXb INT,
    TinhTrang VARCHAR(20),
    FOREIGN KEY (MaSach) REFERENCES DocGia(MaDG),
	FOREIGN KEY (TenSach) REFERENCES DocGia(MaDG)
);

